apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: promtail
  name: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promtail
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: promtail
    spec:
      containers:
        - args:
            - --config.file=/etc/promtail/docker-config.yaml
          image: grafana/promtail:2.1.0
          name: monitoring-promtail
          resources: {}
          volumeMounts:
            - mountPath: /etc/promtail/docker-config.yaml
              name: promtail-claim0
            - mountPath: /var/log/monitoring.log
              name: promtail-claim1
      restartPolicy: Always
      volumes:
        - name: promtail-claim0
          persistentVolumeClaim:
            claimName: promtail-claim0
        - name: promtail-claim1
          persistentVolumeClaim:
            claimName: promtail-claim1
status: {}
