apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: prometheus
    spec:
      containers:
        - args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
          image: prom/prometheus:v2.23.0
          name: monitoring-prometheus
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus
              subPath: prometheus.yml
          # volumeMounts:
          #   - mountPath: /etc/prometheus/prometheus.yml
          #     name: prometheus-claim0
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: prometheus
          name: prometheus
      # volumes:
      #   - name: prometheus-claim0
      #     persistentVolumeClaim:
      #       claimName: prometheus-claim0
status: {}
